const CHUNK_OF_VALIDATION = {
    AVION: "L'avion a été ",
    NOUVEL_AVION: "Le nouvel avion a été ",
    VOL: "Le vol a été ",
    NOUVEAU_VOL: "Le nouveau vol a été ",
    PASSAGER: "Le passager a été",
    NOUVEAU_PASSAGER: "Le nouveau passager a été ",
    BILLET: "Le billet a été",
    NOUVEAU_BILLET: "Le nouveau billet a été ",
    CORRECTEMENT: "correctement ",
    CREE: "créé ",
    MIS_A_JOUR: "mis à jour ",
    SUPPRIME: "supprimé"
}

const VALIDATIONS = {
    AVION_CREE: `${CHUNK_OF_VALIDATION.NOUVEL_AVION}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.CREE}`,
    AVION_MIS_A_JOUR: `${CHUNK_OF_VALIDATION.AVION}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.MIS_A_JOUR}`,
    AVION_SUPPRIME:`${CHUNK_OF_VALIDATION.AVION}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.SUPPRIME}`,
    VOL_CREE: `${CHUNK_OF_VALIDATION.NOUVEAU_VOL}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.CREE}`,
    VOL_MIS_A_JOUR: `${CHUNK_OF_VALIDATION.VOL}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.MIS_A_JOUR}`,
    VOL_SUPPRIME: `${CHUNK_OF_VALIDATION.VOL}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.SUPPRIME}`,
    PASSAGER_CREE: `${CHUNK_OF_VALIDATION.NOUVEAU_PASSAGER}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.CREE}`,
    PASSAGER_MIS_A_JOUR: `${CHUNK_OF_VALIDATION.PASSAGER}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.MIS_A_JOUR}`,
    PASSAGER_SUPPRIME: `${CHUNK_OF_VALIDATION.PASSAGER}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.SUPPRIME}`,
    BILLET_CREE: `${CHUNK_OF_VALIDATION.NOUVEAU_BILLET}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.CREE}`,
    BILLET_MIS_A_JOUR: `${CHUNK_OF_VALIDATION.BILLET}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.MIS_A_JOUR}`,
    BILLET_SUPPRIME: `${CHUNK_OF_VALIDATION.BILLET}${CHUNK_OF_VALIDATION.CORRECTEMENT}${CHUNK_OF_VALIDATION.SUPPRIME}`
};